name: bilbo
description: An advertising project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0
  path_provider: ^2.0.10
  gallery_saver: ^2.3.2
  permission_handler: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Mont/Mont-Regular.otf
